# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainX.ui'
#
# Created by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(893, 675)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Otros/resources/MainGui.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(25.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(414, 489))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.status_bar = QtGui.QStatusBar(MainWindow)
        self.status_bar.setObjectName(_fromUtf8("status_bar"))
        MainWindow.setStatusBar(self.status_bar)
        self.dock_widget = QtGui.QDockWidget(MainWindow)
        self.dock_widget.setMinimumSize(QtCore.QSize(318, 41))
        self.dock_widget.setMaximumSize(QtCore.QSize(518, 524287))
        self.dock_widget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dock_widget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dock_widget.setObjectName(_fromUtf8("dock_widget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.dock_widget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dock_widget)
        self.act_zoom = QtGui.QAction(MainWindow)
        self.act_zoom.setCheckable(True)
        self.act_zoom.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Actions/pictures/change-slice.svg")), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Actions/pictures/zoom.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_zoom.setIcon(icon1)
        self.act_zoom.setObjectName(_fromUtf8("act_zoom"))
        self.act_change_slice = QtGui.QAction(MainWindow)
        self.act_change_slice.setCheckable(True)
        self.act_change_slice.setChecked(False)
        self.act_change_slice.setEnabled(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Actions/pictures/change-slice.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_change_slice.setIcon(icon2)
        self.act_change_slice.setObjectName(_fromUtf8("act_change_slice"))
        self.act_roi_pol = QtGui.QAction(MainWindow)
        self.act_roi_pol.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Actions/pictures/new-pol-roi.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_roi_pol.setIcon(icon3)
        self.act_roi_pol.setObjectName(_fromUtf8("act_roi_pol"))
        self.act_roi_circ = QtGui.QAction(MainWindow)
        self.act_roi_circ.setCheckable(True)
        self.act_roi_circ.setEnabled(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Actions/pictures/new-circ-roi.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_roi_circ.setIcon(icon4)
        self.act_roi_circ.setObjectName(_fromUtf8("act_roi_circ"))
        self.act_roi_auto = QtGui.QAction(MainWindow)
        self.act_roi_auto.setCheckable(True)
        self.act_roi_auto.setEnabled(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Actions/pictures/auto-roi.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_roi_auto.setIcon(icon5)
        self.act_roi_auto.setObjectName(_fromUtf8("act_roi_auto"))
        self.act_get_stats = QtGui.QAction(MainWindow)
        self.act_get_stats.setEnabled(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/Actions/pictures/roi-stats.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_get_stats.setIcon(icon6)
        self.act_get_stats.setObjectName(_fromUtf8("act_get_stats"))
        self.act_select = QtGui.QAction(MainWindow)
        self.act_select.setCheckable(True)
        self.act_select.setChecked(True)
        self.act_select.setEnabled(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/Actions/pictures/select.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_select.setIcon(icon7)
        self.act_select.setObjectName(_fromUtf8("act_select"))
        self.act_dosimetry = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/Actions/pictures/dosimetry.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_dosimetry.setIcon(icon8)
        self.act_dosimetry.setObjectName(_fromUtf8("act_dosimetry"))
        self.act_show_info = QtGui.QAction(MainWindow)
        self.act_show_info.setCheckable(True)
        self.act_show_info.setChecked(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/Actions/pictures/patient-info.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_show_info.setIcon(icon9)
        self.act_show_info.setObjectName(_fromUtf8("act_show_info"))
        self.act_clone_rois = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/Actions/pictures/clone-rois.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_clone_rois.setIcon(icon10)
        self.act_clone_rois.setObjectName(_fromUtf8("act_clone_rois"))
        self.act_phantom = QtGui.QAction(MainWindow)
        self.act_phantom.setEnabled(False)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/Actions/pictures/phantom.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_phantom.setIcon(icon11)
        self.act_phantom.setObjectName(_fromUtf8("act_phantom"))
        self.act_settings = QtGui.QAction(MainWindow)
        self.act_settings.setEnabled(False)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/Actions/pictures/settings.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_settings.setIcon(icon12)
        self.act_settings.setObjectName(_fromUtf8("act_settings"))
        self.actWL = QtGui.QAction(MainWindow)
        self.actWL.setCheckable(True)
        self.actWL.setEnabled(True)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/Actions/pictures/WL.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actWL.setIcon(icon13)
        self.actWL.setObjectName(_fromUtf8("actWL"))
        self.act_exit = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/Actions/pictures/exit.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_exit.setIcon(icon14)
        self.act_exit.setObjectName(_fromUtf8("act_exit"))
        self.act_experimental = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/Actions/pictures/experimental.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_experimental.setIcon(icon15)
        self.act_experimental.setObjectName(_fromUtf8("act_experimental"))

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.act_exit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainGui - Visor Dicom", None))
        self.act_zoom.setText(_translate("MainWindow", "Zoom", None))
        self.act_zoom.setToolTip(_translate("MainWindow", "Zoom image/Move Z", None))
        self.act_change_slice.setText(_translate("MainWindow", "Change image", None))
        self.act_change_slice.setToolTip(_translate("MainWindow", "Navigate between images", None))
        self.act_roi_pol.setText(_translate("MainWindow", "Draw roi", None))
        self.act_roi_pol.setToolTip(_translate("MainWindow", "Draw polygonal roi", None))
        self.act_roi_circ.setText(_translate("MainWindow", "Draw circular roi", None))
        self.act_roi_circ.setToolTip(_translate("MainWindow", "Draw circular roi", None))
        self.act_roi_auto.setText(_translate("MainWindow", "Automatic roi", None))
        self.act_roi_auto.setToolTip(_translate("MainWindow", "Automatically defines a roi", None))
        self.act_get_stats.setText(_translate("MainWindow", "Roi stats", None))
        self.act_get_stats.setToolTip(_translate("MainWindow", "Get roi statistics", None))
        self.act_select.setText(_translate("MainWindow", "Select", None))
        self.act_select.setToolTip(_translate("MainWindow", "selection tool", None))
        self.act_dosimetry.setText(_translate("MainWindow", "Internal dosimetry", None))
        self.act_dosimetry.setToolTip(_translate("MainWindow", "Opens internal dosimetry tool", None))
        self.act_show_info.setText(_translate("MainWindow", "show info", None))
        self.act_clone_rois.setText(_translate("MainWindow", "clone roi(s)", None))
        self.act_clone_rois.setToolTip(_translate("MainWindow", "Clone selected roi(s) to other slices", None))
        self.act_phantom.setText(_translate("MainWindow", "MIRD-5 phantom", None))
        self.act_phantom.setToolTip(_translate("MainWindow", "SPECT/CT image of MIRD-5 phantom", None))
        self.act_settings.setText(_translate("MainWindow", "Settings", None))
        self.act_settings.setToolTip(_translate("MainWindow", "Program settings", None))
        self.actWL.setText(_translate("MainWindow", "Window/Level", None))
        self.actWL.setToolTip(_translate("MainWindow", "Change Window/Level", None))
        self.act_exit.setText(_translate("MainWindow", "Exit", None))
        self.act_exit.setToolTip(_translate("MainWindow", "Exit ViDi", None))
        self.act_experimental.setText(_translate("MainWindow", "Experimental", None))
        self.act_experimental.setToolTip(_translate("MainWindow", "Tools in development or experiences", None))

import icons_rc
