# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'session.ui'
#
# Created by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(451, 337)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frame.sizePolicy().hasHeightForWidth())
        Frame.setSizePolicy(sizePolicy)
        Frame.setMinimumSize(QtCore.QSize(0, 125))
        Frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.gridLayoutWidget = QtGui.QWidget(Frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(2, 2, 441, 310))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.grid_layout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.grid_layout.setMargin(10)
        self.grid_layout.setObjectName(_fromUtf8("grid_layout"))
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.grid_layout.addWidget(self.label, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.grid_layout.addWidget(self.label_3, 1, 2, 1, 1)
        self.sp_session = QtGui.QSpinBox(self.gridLayoutWidget)
        self.sp_session.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sp_session.sizePolicy().hasHeightForWidth())
        self.sp_session.setSizePolicy(sizePolicy)
        self.sp_session.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sp_session.setMinimum(1)
        self.sp_session.setObjectName(_fromUtf8("sp_session"))
        self.grid_layout.addWidget(self.sp_session, 0, 2, 1, 1)
        self.sp_activity = QtGui.QSpinBox(self.gridLayoutWidget)
        self.sp_activity.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sp_activity.sizePolicy().hasHeightForWidth())
        self.sp_activity.setSizePolicy(sizePolicy)
        self.sp_activity.setMaximumSize(QtCore.QSize(80, 16777215))
        self.sp_activity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sp_activity.setReadOnly(False)
        self.sp_activity.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.sp_activity.setMaximum(99999)
        self.sp_activity.setObjectName(_fromUtf8("sp_activity"))
        self.grid_layout.addWidget(self.sp_activity, 1, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.grid_layout.addWidget(self.label_2, 2, 0, 1, 1)
        self.dt_admin = QtGui.QDateTimeEdit(self.gridLayoutWidget)
        self.dt_admin.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dt_admin.sizePolicy().hasHeightForWidth())
        self.dt_admin.setSizePolicy(sizePolicy)
        self.dt_admin.setMaximumSize(QtCore.QSize(140, 16777215))
        self.dt_admin.setTime(QtCore.QTime(0, 0, 0))
        self.dt_admin.setCalendarPopup(True)
        self.dt_admin.setObjectName(_fromUtf8("dt_admin"))
        self.grid_layout.addWidget(self.dt_admin, 2, 1, 1, 2)
        self.tx_isotope = QtGui.QLineEdit(self.gridLayoutWidget)
        self.tx_isotope.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_isotope.sizePolicy().hasHeightForWidth())
        self.tx_isotope.setSizePolicy(sizePolicy)
        self.tx_isotope.setMinimumSize(QtCore.QSize(60, 0))
        self.tx_isotope.setMaximumSize(QtCore.QSize(60, 16777215))
        self.tx_isotope.setObjectName(_fromUtf8("tx_isotope"))
        self.grid_layout.addWidget(self.tx_isotope, 1, 1, 1, 1)
        self.tx_notes = QtGui.QPlainTextEdit(self.gridLayoutWidget)
        self.tx_notes.setObjectName(_fromUtf8("tx_notes"))
        self.grid_layout.addWidget(self.tx_notes, 4, 0, 1, 4)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.grid_layout.addWidget(self.label_8, 1, 0, 1, 1)
        self.tx_n_treatment = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_n_treatment.sizePolicy().hasHeightForWidth())
        self.tx_n_treatment.setSizePolicy(sizePolicy)
        self.tx_n_treatment.setMaximumSize(QtCore.QSize(50, 16777215))
        self.tx_n_treatment.setObjectName(_fromUtf8("tx_n_treatment"))
        self.grid_layout.addWidget(self.tx_n_treatment, 3, 3, 1, 1)
        self.ck_locked = QtGui.QCheckBox(self.gridLayoutWidget)
        self.ck_locked.setObjectName(_fromUtf8("ck_locked"))
        self.grid_layout.addWidget(self.ck_locked, 3, 2, 1, 1)
        self.act_edit = QtGui.QAction(Frame)
        self.act_edit.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/database/resources/edit.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_edit.setIcon(icon)
        self.act_edit.setObjectName(_fromUtf8("act_edit"))
        self.act_undo = QtGui.QAction(Frame)
        self.act_undo.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/database/resources/undo.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_undo.setIcon(icon1)
        self.act_undo.setObjectName(_fromUtf8("act_undo"))
        self.act_notes = QtGui.QAction(Frame)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/database/resources/notas.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_notes.setIcon(icon2)
        self.act_notes.setObjectName(_fromUtf8("act_notes"))
        self.act_lock = QtGui.QAction(Frame)
        self.act_lock.setEnabled(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/database/resources/lock.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_lock.setIcon(icon3)
        self.act_lock.setObjectName(_fromUtf8("act_lock"))
        self.label.setBuddy(self.sp_session)
        self.label_3.setBuddy(self.sp_activity)
        self.label_2.setBuddy(self.dt_admin)
        self.label_8.setBuddy(self.tx_isotope)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(_translate("Frame", "Frame", None))
        self.label.setText(_translate("Frame", "Session #:", None))
        self.label_3.setText(_translate("Frame", "Activity (MBq) :", None))
        self.label_2.setText(_translate("Frame", "Admin. date/time:", None))
        self.dt_admin.setDisplayFormat(_translate("Frame", "dd/MM/yy HH:mm", None))
        self.label_8.setText(_translate("Frame", "Isotope:", None))
        self.ck_locked.setText(_translate("Frame", "locked", None))
        self.act_edit.setText(_translate("Frame", "Edit/Update", None))
        self.act_edit.setToolTip(_translate("Frame", "Edit/Update record", None))
        self.act_undo.setText(_translate("Frame", "Undo", None))
        self.act_undo.setToolTip(_translate("Frame", "Undo edition and lock record", None))
        self.act_notes.setText(_translate("Frame", "Notes", None))
        self.act_lock.setText(_translate("Frame", "Lock", None))
        self.act_lock.setToolTip(_translate("Frame", "Lock record (Finished treatment)", None))

import icons_rc
