# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'treatment.ui'
#
# Created by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(451, 389)
        Frame.setMaximumSize(QtCore.QSize(16777215, 500))
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.gridLayoutWidget = QtGui.QWidget(Frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 441, 305))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.grid_layout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.grid_layout.setMargin(10)
        self.grid_layout.setObjectName(_fromUtf8("grid_layout"))
        self.tx_notes = QtGui.QPlainTextEdit(self.gridLayoutWidget)
        self.tx_notes.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tx_notes.setObjectName(_fromUtf8("tx_notes"))
        self.grid_layout.addWidget(self.tx_notes, 5, 0, 1, 5)
        self.tx_diagnostic = QtGui.QLineEdit(self.gridLayoutWidget)
        self.tx_diagnostic.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_diagnostic.sizePolicy().hasHeightForWidth())
        self.tx_diagnostic.setSizePolicy(sizePolicy)
        self.tx_diagnostic.setMinimumSize(QtCore.QSize(250, 0))
        self.tx_diagnostic.setInputMask(_fromUtf8(""))
        self.tx_diagnostic.setText(_fromUtf8(""))
        self.tx_diagnostic.setPlaceholderText(_fromUtf8(""))
        self.tx_diagnostic.setObjectName(_fromUtf8("tx_diagnostic"))
        self.grid_layout.addWidget(self.tx_diagnostic, 2, 1, 1, 4)
        self.tx_schedule = QtGui.QLineEdit(self.gridLayoutWidget)
        self.tx_schedule.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_schedule.sizePolicy().hasHeightForWidth())
        self.tx_schedule.setSizePolicy(sizePolicy)
        self.tx_schedule.setMaximumSize(QtCore.QSize(150, 16777215))
        self.tx_schedule.setObjectName(_fromUtf8("tx_schedule"))
        self.grid_layout.addWidget(self.tx_schedule, 3, 1, 1, 1)
        self.tx_physician = QtGui.QLineEdit(self.gridLayoutWidget)
        self.tx_physician.setEnabled(False)
        self.tx_physician.setMinimumSize(QtCore.QSize(200, 0))
        self.tx_physician.setObjectName(_fromUtf8("tx_physician"))
        self.grid_layout.addWidget(self.tx_physician, 1, 1, 1, 4)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.grid_layout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.grid_layout.addWidget(self.label_2, 2, 0, 1, 1)
        self.dt_start_date = QtGui.QDateEdit(self.gridLayoutWidget)
        self.dt_start_date.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dt_start_date.sizePolicy().hasHeightForWidth())
        self.dt_start_date.setSizePolicy(sizePolicy)
        self.dt_start_date.setMaximumSize(QtCore.QSize(120, 16777215))
        self.dt_start_date.setCalendarPopup(True)
        self.dt_start_date.setObjectName(_fromUtf8("dt_start_date"))
        self.grid_layout.addWidget(self.dt_start_date, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.grid_layout.addWidget(self.label_4, 3, 0, 1, 1)
        self.dt_end_date = QtGui.QDateEdit(self.gridLayoutWidget)
        self.dt_end_date.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dt_end_date.sizePolicy().hasHeightForWidth())
        self.dt_end_date.setSizePolicy(sizePolicy)
        self.dt_end_date.setMaximumSize(QtCore.QSize(120, 16777215))
        self.dt_end_date.setCalendarPopup(True)
        self.dt_end_date.setObjectName(_fromUtf8("dt_end_date"))
        self.grid_layout.addWidget(self.dt_end_date, 0, 4, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.grid_layout.addWidget(self.label_5, 0, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.grid_layout.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.grid_layout.addWidget(self.label_6, 3, 2, 1, 1)
        self.tx_pharmaceutical = QtGui.QLineEdit(self.gridLayoutWidget)
        self.tx_pharmaceutical.setEnabled(False)
        self.tx_pharmaceutical.setObjectName(_fromUtf8("tx_pharmaceutical"))
        self.grid_layout.addWidget(self.tx_pharmaceutical, 3, 3, 1, 2)
        self.tx_n_patient = QtGui.QLineEdit(self.gridLayoutWidget)
        self.tx_n_patient.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_n_patient.sizePolicy().hasHeightForWidth())
        self.tx_n_patient.setSizePolicy(sizePolicy)
        self.tx_n_patient.setMaximumSize(QtCore.QSize(100, 16777215))
        self.tx_n_patient.setObjectName(_fromUtf8("tx_n_patient"))
        self.grid_layout.addWidget(self.tx_n_patient, 4, 0, 1, 1)
        self.ck_locked = QtGui.QCheckBox(self.gridLayoutWidget)
        self.ck_locked.setEnabled(False)
        self.ck_locked.setChecked(False)
        self.ck_locked.setObjectName(_fromUtf8("ck_locked"))
        self.grid_layout.addWidget(self.ck_locked, 4, 1, 1, 1)
        self.act_edit = QtGui.QAction(Frame)
        self.act_edit.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/database/resources/edit.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_edit.setIcon(icon)
        self.act_edit.setObjectName(_fromUtf8("act_edit"))
        self.act_undo = QtGui.QAction(Frame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/database/resources/undo.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_undo.setIcon(icon1)
        self.act_undo.setObjectName(_fromUtf8("act_undo"))
        self.act_notes = QtGui.QAction(Frame)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/database/resources/notas.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_notes.setIcon(icon2)
        self.act_notes.setObjectName(_fromUtf8("act_notes"))
        self.act_lock = QtGui.QAction(Frame)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/database/resources/lock.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_lock.setIcon(icon3)
        self.act_lock.setObjectName(_fromUtf8("act_lock"))
        self.label.setBuddy(self.tx_physician)
        self.label_2.setBuddy(self.tx_diagnostic)
        self.label_4.setBuddy(self.tx_schedule)
        self.label_3.setBuddy(self.dt_start_date)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(_translate("Frame", "Frame", None))
        self.tx_schedule.setPlaceholderText(_translate("Frame", "Times, Activity...", None))
        self.label.setText(_translate("Frame", "Ref. Physician:", None))
        self.label_2.setText(_translate("Frame", "Diagnostic:", None))
        self.label_4.setText(_translate("Frame", "Schedule:", None))
        self.label_5.setText(_translate("Frame", "/", None))
        self.label_3.setText(_translate("Frame", "Start/End date:", None))
        self.label_6.setText(_translate("Frame", "Pharmaceutical:", None))
        self.tx_pharmaceutical.setPlaceholderText(_translate("Frame", "Pharmaceutical...", None))
        self.ck_locked.setText(_translate("Frame", "Locked", None))
        self.act_edit.setText(_translate("Frame", "Edit/Update", None))
        self.act_edit.setToolTip(_translate("Frame", "Edit/Update record", None))
        self.act_undo.setText(_translate("Frame", "Undo", None))
        self.act_undo.setToolTip(_translate("Frame", "Undo edition and lock record", None))
        self.act_notes.setText(_translate("Frame", "Notes", None))
        self.act_lock.setText(_translate("Frame", "Lock", None))
        self.act_lock.setToolTip(_translate("Frame", "Lock record (Finished treatment)", None))

import icons_rc
